name: ECS Deployment

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: is-even-api
  ECS_SERVICE: is-even-api
  ECS_CLUSTER: test-cluster
  ECS_TASK_DEFINITION: .aws/task_definition.json
  CONTAINER_NAME: is-even-api

jobs:
  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: bridge_oauth_backend
          path: /home/runner/work/bridge_oauth_backend/bridge_oauth_backend/target/release/bridge_backend_auth
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Render task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
